### ISSUE TITLE
AWS installing necessary libraries

### ISSUE THREAD

**Issue by florianbepunkt** [tpisto/pdf-fill-form#36]
I have a hard time installing this module on AWS Elastic Beanstalk, basically npm install fails when trying to install this package… my guess is, it has to do with the libraries that are needed to install prior before installing the module itself via npm.

I can specify packages that get installed prior npm install, but apt-get is not available

But I can specify yum packages in my .ebextensions config gile like so
```
packages: 
  yum:
    libmemcached: [] 
    ruby-devel: []
    gcc: []
```

But I have no idea, what yum packages would be needed.

using these don't work. Can you help out?

```
packages:
  yum:
    libpoppler-qt5-dev: []
    libcairo2-dev: []
```
